version: "3.7"
services:
  tdsvm_:
    container_name: svm
    build: .
    image: svm
    network_mode: "host"
    restart: always
    # environment:
    #   CONFIGS: ../conf_folder/configs.json
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./:/retrain
      - ../doccano_project_data/:/doccano_project_data