version: "3.7"
services:
  retrain_model:
    container_name: retrain
    build: .
    image: retrain
    network_mode: "host"
    restart: always
    # environment:
    #   CONFIGS: ../conf_folder/configs.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    volumes:
      - ../../doccano_project_data/:/../doccano_project_data
      - ../:/retrain
